version: '3.9'

services:
  server:
    image: digiscript:latest
    container_name: DS-Server
    environment:
      DOCKER_DEPLOYMENT: "true"
    ports:
      - 8080:8080
    volumes:
      - dssrv:/server/conf

volumes:
  dssrv: