version: '3.9'

services:
  server:
    image: digiscript:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: DigiScript
    ports:
      - 8080:8080
    volumes:
      - dssrv:/server/conf
volumes:
  dssrv:
