version: '3.9'

services:
  server:
    image: digiscript:latest
    container_name: DS-Server
    environment:
      DOCKER_DEPLOYMENT: "true"
    ports:
      - 8080:8080
    volumes:
      - dssrv:/server/conf

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./reporting/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
      - node-exporter
      - server

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
      - '--collector.systemd'
      - '--collector.processes'
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8090:8080
    restart: always
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    user: '472'
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./reporting/grafana/provisioning:/etc/grafana/provisioning/
    env_file:
      - ./reporting/grafana/config.env
    ports:
      - 3000:3000
    depends_on:
      - prometheus

volumes:
  dssrv:
  prometheus_data:
  grafana_data: