"""add script draft and is_cutting for collaborative editing

Revision ID: 0b3fa405e05b
Revises: e96bdd11ca42
Create Date: 2026-09-04 12:36:04.600853

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0b3fa405e05b"
down_revision: Union[str, None] = "e96bdd11ca42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "script_drafts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("data_path", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.Column("last_editor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_editor_id"],
            ["user.id"],
            name=op.f("fk_script_drafts_last_editor_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["script_revisions.id"],
            name=op.f("fk_script_drafts_revision_id_script_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_script_drafts")),
        sa.UniqueConstraint("revision_id", name=op.f("uq_script_drafts_revision_id")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_cutting", sa.Boolean(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_sessions_is_cutting"), ["is_cutting"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_is_cutting"))
        batch_op.drop_column("is_cutting")

    op.drop_table("script_drafts")
    # ### end Alembic commands ###
