"""add preferred_ui to user_settings

Revision ID: 11311df29aa4
Revises: 4fbfeaba60ae
Create Date: 2026-05-19 23:24:51.376973

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "11311df29aa4"
down_revision: Union[str, None] = "4fbfeaba60ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("preferred_ui", sa.String(), nullable=True))
        batch_op.create_check_constraint(
            "ck_user_settings_preferred_ui",
            "preferred_ui IS NULL OR preferred_ui IN ('old', 'new')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_constraint("ck_user_settings_preferred_ui", type_="check")
        batch_op.drop_column("preferred_ui")

    # ### end Alembic commands ###
