"""Add crew table

Revision ID: 18660a2d5398
Revises: 8c78b9c89ee6
Create Date: 2025-06-22 09:57:46.277311

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18660a2d5398"
down_revision: Union[str, None] = "8c78b9c89ee6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crew",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_crew_show_id_shows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crew")
    # ### end Alembic commands ###
