"""User deletion

Revision ID: 29471f7cf7d2
Revises: be353176c064
Create Date: 2025-04-23 00:01:32.182458

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29471f7cf7d2"
down_revision: Union[str, None] = "be353176c064"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_sessions_user_id_user"),
            "user",
            ["user_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("showsession", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_showsession_user_id_user"),
            "user",
            ["user_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_user_settings_user_id_user"),
            "user",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_user_settings_user_id_user"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_user_settings_user_id_user", "user", ["user_id"], ["id"]
        )

    with op.batch_alter_table("showsession", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_showsession_user_id_user"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_sessions_user_id_user"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    # ### end Alembic commands ###
