"""Add table_page_sizes to user_settings

Revision ID: 390f0ab54425
Revises: 3f2343a8a936
Create Date: 2026-06-09 01:05:20.965630

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "390f0ab54425"
down_revision: Union[str, None] = "3f2343a8a936"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("table_page_sizes", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_column("table_page_sizes")

    # ### end Alembic commands ###
