"""add_cascade_delete_to_script_foreign_keys

Revision ID: 3f5e49494531
Revises: 8c78b9c89ee6
Create Date: 2025-08-24 22:49:25.592155

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f5e49494531"
down_revision: Union[str, None] = "8c78b9c89ee6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add ON DELETE CASCADE to foreign key constraints for script_lines relationships."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Update script_line_parts foreign key constraint
    with op.batch_alter_table("script_line_parts", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_script_line_parts_line_id_script_lines", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_script_line_parts_line_id_script_lines",
            "script_lines",
            ["line_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # 2. Update script_line_revision_association foreign key constraints
    with op.batch_alter_table(
        "script_line_revision_association", schema=None
    ) as batch_op:
        # Drop existing foreign key constraints
        batch_op.drop_constraint(
            "fk_script_line_revision_association_line_id_script_lines",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_script_line_revision_association_next_line_id_script_lines",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_script_line_revision_association_previous_line_id_script_lines",
            type_="foreignkey",
        )

        # Create new foreign key constraints with CASCADE
        batch_op.create_foreign_key(
            "fk_script_line_revision_association_line_id_script_lines",
            "script_lines",
            ["line_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_script_line_revision_association_next_line_id_script_lines",
            "script_lines",
            ["next_line_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_script_line_revision_association_previous_line_id_script_lines",
            "script_lines",
            ["previous_line_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # 3. Update script_cue_association foreign key constraint
    with op.batch_alter_table("script_cue_association", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_script_cue_association_line_id_script_lines", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_script_cue_association_line_id_script_lines",
            "script_lines",
            ["line_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove ON DELETE CASCADE from foreign key constraints for script_lines relationships."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Revert script_line_parts foreign key constraint
    with op.batch_alter_table("script_line_parts", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_script_line_parts_line_id_script_lines", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_script_line_parts_line_id_script_lines",
            "script_lines",
            ["line_id"],
            ["id"],
        )

    # 2. Revert script_line_revision_association foreign key constraints
    with op.batch_alter_table(
        "script_line_revision_association", schema=None
    ) as batch_op:
        # Drop CASCADE foreign key constraints
        batch_op.drop_constraint(
            "fk_script_line_revision_association_line_id_script_lines",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_script_line_revision_association_next_line_id_script_lines",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_script_line_revision_association_previous_line_id_script_lines",
            type_="foreignkey",
        )

        # Create original foreign key constraints without CASCADE
        batch_op.create_foreign_key(
            "fk_script_line_revision_association_line_id_script_lines",
            "script_lines",
            ["line_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_script_line_revision_association_next_line_id_script_lines",
            "script_lines",
            ["next_line_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_script_line_revision_association_previous_line_id_script_lines",
            "script_lines",
            ["previous_line_id"],
            ["id"],
        )

    # 3. Revert script_cue_association foreign key constraint
    with op.batch_alter_table("script_cue_association", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_script_cue_association_line_id_script_lines", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_script_cue_association_line_id_script_lines",
            "script_lines",
            ["line_id"],
            ["id"],
        )

    # ### end Alembic commands ###
