"""Add is_cutting to sessions

Revision ID: 43fcd5292e0f
Revises: 888565843a87
Create Date: 2026-02-13 12:11:35.226948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fcd5292e0f'
down_revision: Union[str, None] = '888565843a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cutting', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sessions_is_cutting'), ['is_cutting'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_is_cutting'))
        batch_op.drop_column('is_cutting')

    # ### end Alembic commands ###
