"""Add script revision association to show session

Revision ID: 4400e44b4455
Revises: 4632b14b6e67
Create Date: 2026-01-08 00:12:25.730083

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4400e44b4455"
down_revision: Union[str, None] = "4632b14b6e67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable initially (required for backfill)
    with op.batch_alter_table("showsession", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("script_revision_id", sa.Integer(), nullable=True)
        )
        batch_op.alter_column("show_id", existing_type=sa.INTEGER(), nullable=False)

    # Step 2: Backfill script_revision_id from script.current_revision
    connection = op.get_bind()

    # Check for shows with multiple scripts (should be 1:1 relationship)
    multi_script_shows = connection.execute(
        sa.text("""
            SELECT show_id, COUNT(*) as script_count
            FROM script
            GROUP BY show_id
            HAVING COUNT(*) > 1
        """)
    ).fetchall()

    if multi_script_shows:
        print("Warning: Found shows with multiple scripts (expected 1:1 relationship):")
        for row in multi_script_shows:
            print(f"  Show ID {row[0]}: {row[1]} scripts")
        print("Using the first script (ordered by ID) for each show...")

    # Backfill sessions with script_revision_id
    # For shows with multiple scripts, use the first script (ordered by ID)
    connection.execute(
        sa.text("""
            UPDATE showsession
            SET script_revision_id = (
                SELECT s.current_revision
                FROM script s
                WHERE s.show_id = showsession.show_id
                ORDER BY s.id
                LIMIT 1
            )
            WHERE script_revision_id IS NULL
            AND EXISTS (
                SELECT 1 FROM script s
                WHERE s.show_id = showsession.show_id
                AND s.current_revision IS NOT NULL
            )
        """)
    )

    # Check for sessions that couldn't be backfilled
    orphaned_sessions = connection.execute(
        sa.text("""
            SELECT id, show_id
            FROM showsession
            WHERE script_revision_id IS NULL
        """)
    ).fetchall()

    if orphaned_sessions:
        print("\nERROR: Found sessions without valid script revisions:")
        for row in orphaned_sessions:
            print(f"  Session ID {row[0]}, Show ID {row[1]}")
        raise Exception(
            "Cannot complete migration: Some sessions do not have a corresponding "
            "script with a current_revision. Please either delete these sessions or "
            "ensure all shows have a script with a current_revision set."
        )

    # Step 3: Make column non-nullable and add foreign key constraint
    with op.batch_alter_table("showsession", schema=None) as batch_op:
        batch_op.alter_column("script_revision_id", nullable=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_showsession_script_revision_id_script_revisions"),
            "script_revisions",
            ["script_revision_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("showsession", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_showsession_script_revision_id_script_revisions"),
            type_="foreignkey",
        )
        batch_op.alter_column("show_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_column("script_revision_id")

    # ### end Alembic commands ###
