"""Add session tags and associations

Revision ID: 4632b14b6e67
Revises: 9f76c42e225e
Create Date: 2026-01-06 01:53:50.057901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4632b14b6e67"
down_revision: Union[str, None] = "9f76c42e225e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=True),
        sa.Column("tag", sa.String(length=255), nullable=False),
        sa.Column("colour", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
            name=op.f("fk_session_tags_show_id_shows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_tags")),
    )
    op.create_table(
        "session_tag_associations",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["showsession.id"],
            name=op.f("fk_session_tag_associations_session_id_showsession"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["session_tags.id"],
            name=op.f("fk_session_tag_associations_tag_id_session_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "session_id", "tag_id", name=op.f("pk_session_tag_associations")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_tag_associations")
    op.drop_table("session_tags")
    # ### end Alembic commands ###
