"""Add compiled scripts table

Revision ID: 49df18ea818d
Revises: f154c79d86de
Create Date: 2025-06-10 17:30:55.412438

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49df18ea818d"
down_revision: Union[str, None] = "f154c79d86de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compiled_scripts",
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("data_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["script_revisions.id"],
            name=op.f("fk_compiled_scripts_revision_id_script_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("revision_id", name=op.f("pk_compiled_scripts")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("compiled_scripts")
    # ### end Alembic commands ###
