"""Add compressed_data field to script_revisions

Revision ID: 4e5d11ea7094
Revises: f154c79d86de
Create Date: 2025-05-26 00:18:34.682053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5d11ea7094'
down_revision: Union[str, None] = 'f154c79d86de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_revisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compressed_data', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_revisions', schema=None) as batch_op:
        batch_op.drop_column('compressed_data')

    # ### end Alembic commands ###
