"""add_character_combined_dropdown_to_user_settings

Revision ID: 4fbfeaba60ae
Revises: c515969c1a51
Create Date: 2026-05-13 00:56:16.000156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbfeaba60ae'
down_revision: Union[str, None] = 'c515969c1a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first so existing rows can be backfilled
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_combined_dropdown', sa.Boolean(), nullable=True))

    # Backfill existing rows to False
    op.execute(
        'UPDATE user_settings SET character_combined_dropdown = 0 WHERE character_combined_dropdown IS NULL'
    )

    # Make column non-nullable
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column(
            'character_combined_dropdown', existing_type=sa.Boolean(), nullable=False
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('character_combined_dropdown')

    # ### end Alembic commands ###
