"""add unique constraints to allocation tables

Revision ID: 625ac1e96e88
Revises: 9849eb6d381a
Create Date: 2026-01-16 00:31:42.000334

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "625ac1e96e88"
down_revision: Union[str, None] = "9849eb6d381a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("props_allocation", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_props_scene", ["props_id", "scene_id"])

    with op.batch_alter_table("scenery_allocation", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_scenery_scene", ["scenery_id", "scene_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenery_allocation", schema=None) as batch_op:
        batch_op.drop_constraint("uq_scenery_scene", type_="unique")

    with op.batch_alter_table("props_allocation", schema=None) as batch_op:
        batch_op.drop_constraint("uq_props_scene", type_="unique")

    # ### end Alembic commands ###
