"""Add cue_position_right setting

Revision ID: 7cfa4709bb41
Revises: ff9f875915b6
Create Date: 2025-05-03 17:52:31.859325

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cfa4709bb41"
down_revision: Union[str, None] = "ff9f875915b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column(
            "cue_position_right", sa.Boolean(), nullable=True, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "cue_position_right")
    # ### end Alembic commands ###
