"""Add interval state to show session

Revision ID: 7fe8320b38c9
Revises: 7df32f85a5a2
Create Date: 2025-04-28 00:30:11.281143

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fe8320b38c9"
down_revision: Union[str, None] = "7df32f85a5a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "showinterval",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("act_id", sa.Integer(), nullable=True),
        sa.Column("start_datetime", sa.DateTime(), nullable=True),
        sa.Column("end_datetime", sa.DateTime(), nullable=True),
        sa.Column("initial_length", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["act_id"],
            ["act.id"],
            name=op.f("fk_showinterval_act_id_act"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["showsession.id"],
            name=op.f("fk_showinterval_session_id_showsession"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_showinterval")),
    )
    with op.batch_alter_table("showsession", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("current_interval_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_showsession_current_interval_id_showinterval"),
            "showinterval",
            ["current_interval_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("showsession", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_showsession_current_interval_id_showinterval"),
            type_="foreignkey",
        )
        batch_op.drop_column("current_interval_id")

    op.drop_table("showinterval")
    # ### end Alembic commands ###
