"""add_cue_groups

Revision ID: 863020cc72da
Revises: 390f0ab54425
Create Date: 2026-06-22 23:49:42.070778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "863020cc72da"
down_revision: Union[str, None] = "390f0ab54425"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cue_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cue_type_id", sa.Integer(), nullable=False),
        sa.Column("label_override", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["cue_type_id"],
            ["cuetypes.id"],
            name=op.f("fk_cue_groups_cue_type_id_cuetypes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cue_groups")),
    )
    with op.batch_alter_table("script_cue_association", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("sort_order", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_script_cue_association_group_id"), ["group_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_script_cue_association_group_id_cue_groups"),
            "cue_groups",
            ["group_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("script_cue_association", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_script_cue_association_group_id_cue_groups"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_script_cue_association_group_id"))
        batch_op.drop_column("sort_order")
        batch_op.drop_column("group_id")

    op.drop_table("cue_groups")
    # ### end Alembic commands ###
