"""add script draft table

Revision ID: 888565843a87
Revises: fbb1b6bd8707
Create Date: 2026-02-11 15:08:34.017143

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "888565843a87"
down_revision: Union[str, None] = "fbb1b6bd8707"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "script_drafts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("data_path", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.Column("last_editor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_editor_id"],
            ["user.id"],
            name=op.f("fk_script_drafts_last_editor_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["script_revisions.id"],
            name=op.f("fk_script_drafts_revision_id_script_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_script_drafts")),
        sa.UniqueConstraint("revision_id", name=op.f("uq_script_drafts_revision_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("script_drafts")
    # ### end Alembic commands ###
