"""Add scenery and props

Revision ID: 9161f286a179
Revises: 18660a2d5398
Create Date: 2025-06-22 10:50:06.435076

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9161f286a179"
down_revision: Union[str, None] = "18660a2d5398"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "props",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_props_show_id_shows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_props")),
    )
    op.create_table(
        "scenery",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_scenery_show_id_shows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenery")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenery")
    op.drop_table("props")
    # ### end Alembic commands ###
