"""Add prop and scenery types

Revision ID: 9849eb6d381a
Revises: fa27b233d26c
Create Date: 2026-01-14 01:01:31.586812

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9849eb6d381a"
down_revision: Union[str, None] = "fa27b233d26c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prop_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_prop_type_show_id_shows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prop_type")),
    )
    op.create_table(
        "scenery_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_scenery_type_show_id_shows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenery_type")),
    )
    with op.batch_alter_table("crew", schema=None) as batch_op:
        batch_op.alter_column("first_name", existing_type=sa.String(), nullable=False)

    with op.batch_alter_table("props", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prop_type_id", sa.Integer(), nullable=False))
        batch_op.alter_column("name", existing_type=sa.String(), nullable=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_props_prop_type_id_prop_type"),
            "prop_type",
            ["prop_type_id"],
            ["id"],
        )

    with op.batch_alter_table("scenery", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scenery_type_id", sa.Integer(), nullable=False))
        batch_op.alter_column("name", existing_type=sa.String(), nullable=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_scenery_scenery_type_id_scenery_type"),
            "scenery_type",
            ["scenery_type_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenery", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scenery_scenery_type_id_scenery_type"), type_="foreignkey"
        )
        batch_op.alter_column("name", existing_type=sa.String(), nullable=True)
        batch_op.drop_column("scenery_type_id")

    with op.batch_alter_table("props", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_props_prop_type_id_prop_type"), type_="foreignkey"
        )
        batch_op.alter_column("name", existing_type=sa.String(), nullable=True)
        batch_op.drop_column("prop_type_id")

    with op.batch_alter_table("crew", schema=None) as batch_op:
        batch_op.alter_column("first_name", existing_type=sa.String(), nullable=True)

    op.drop_table("scenery_type")
    op.drop_table("prop_type")
    # ### end Alembic commands ###
