"""Add stage direction styles

Revision ID: a44e01459595
Revises: d4f66f58158b
Create Date: 2025-04-13 23:19:47.362110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44e01459595'
down_revision: Union[str, None] = 'd4f66f58158b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_direction_styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('bold', sa.Boolean(), nullable=True),
    sa.Column('italic', sa.Boolean(), nullable=True),
    sa.Column('underline', sa.Boolean(), nullable=True),
    sa.Column('text_format', sa.String(), nullable=True),
    sa.Column('text_colour', sa.String(), nullable=True),
    sa.Column('enable_background_colour', sa.Boolean(), nullable=True),
    sa.Column('background_colour', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], name=op.f('fk_stage_direction_styles_script_id_script')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_direction_styles'))
    )
    with op.batch_alter_table('stage_direction_styles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_direction_styles_script_id'), ['script_id'], unique=False)

    with op.batch_alter_table('script_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_direction_style_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_script_lines_stage_direction_style_id_stage_direction_styles'), 'stage_direction_styles', ['stage_direction_style_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_lines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_script_lines_stage_direction_style_id_stage_direction_styles'), type_='foreignkey')
        batch_op.drop_column('stage_direction_style_id')

    with op.batch_alter_table('stage_direction_styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_direction_styles_script_id'))

    op.drop_table('stage_direction_styles')
    # ### end Alembic commands ###
