"""Fix session table foreign key reference

Revision ID: a4d42ccfb71a
Revises: 29471f7cf7d2
Create Date: 2025-04-25 01:38:42.331417

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4d42ccfb71a"
down_revision: Union[str, None] = "29471f7cf7d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("showsession", schema=None) as batch_op:
        try:
            batch_op.drop_constraint(None, type_="foreignkey")
        except IndexError:
            pass
        batch_op.create_foreign_key(
            batch_op.f("fk_showsession_client_internal_id_sessions"),
            "sessions",
            ["client_internal_id"],
            ["internal_id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("showsession", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_showsession_client_internal_id_sessions"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "sessions", ["client_internal_id"], ["internal_id"]
        )

    # ### end Alembic commands ###
