"""Remove script autosave settings

Revision ID: b3b3422cd1fe
Revises: d3e9f0c1a2b4
Create Date: 2026-03-04 23:45:10.922715

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b3b3422cd1fe"
down_revision: Union[str, None] = "d3e9f0c1a2b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_column("enable_script_auto_save")
        batch_op.drop_column("script_auto_save_interval")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("script_auto_save_interval", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("enable_script_auto_save", sa.BOOLEAN(), nullable=True)
        )

    # ### end Alembic commands ###
