"""Rename user_settings table to user_overrides

Revision ID: bb9b28a04946
Revises: 7fe8320b38c9
Create Date: 2025-05-02 11:57:59.617548

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb9b28a04946"
down_revision: Union[str, None] = "7fe8320b38c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("user_settings", "user_overrides")
    with op.batch_alter_table("user_overrides", schema=None) as batch_op:
        batch_op.drop_index("ix_user_settings_settings_type")
        batch_op.drop_index("ix_user_settings_user_id")
        batch_op.create_index(
            batch_op.f("ix_user_overrides_settings_type"),
            ["settings_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_overrides_user_id"), ["user_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_overrides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_overrides_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_overrides_settings_type"))
        batch_op.create_index("ix_user_settings_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            "ix_user_settings_settings_type", ["settings_type"], unique=False
        )
    op.rename_table("user_overrides", "user_settings")
    # ### end Alembic commands ###
