"""Detach users from shows

Revision ID: be353176c064
Revises: a39ac9e9f085
Create Date: 2025-04-20 22:27:07.342092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be353176c064'
down_revision: Union[str, None] = 'a39ac9e9f085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_show_id')
        try:
            batch_op.drop_constraint(None, type_='foreignkey')
        except IndexError:
            pass
        batch_op.drop_column('show_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'shows', ['show_id'], ['id'])
        batch_op.create_index('ix_user_show_id', ['show_id'], unique=False)

    # ### end Alembic commands ###
