"""Add console_log_level to user_settings

Revision ID: c1db8c1f4e37
Revises: fbb1b6bd8707
Create Date: 2026-02-20 22:51:22.081714

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c1db8c1f4e37"
down_revision: Union[str, None] = "fbb1b6bd8707"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "console_log_level",
                sa.String(),
                nullable=False,
                server_default="WARN",
            )
        )
        batch_op.create_check_constraint(
            "ck_user_settings_console_log_level",
            "console_log_level IN ('TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR', 'SILENT')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_constraint("ck_user_settings_console_log_level", type_="check")
        batch_op.drop_column("console_log_level")

    # ### end Alembic commands ###
