"""Add CASCADE delete to script revision associations

Revision ID: c952e582dcaf
Revises: 49df18ea818d
Create Date: 2025-06-14 23:07:26.917718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c952e582dcaf'
down_revision: Union[str, None] = '49df18ea818d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
