"""add_line_position_to_cue_association

Revision ID: d11cd9306d4b
Revises: 863020cc72da
Create Date: 2026-06-27 13:42:07.205049

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d11cd9306d4b"
down_revision: Union[str, None] = "863020cc72da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("script_cue_association", schema=None) as batch_op:
        batch_op.add_column(sa.Column("line_position", sa.Integer(), nullable=True))

    # ### end Alembic commands ###

    # Backfill existing data: use cue_id as a creation-order proxy.
    # Individual cues and group member cues all live in the same auto-increment
    # table, so cue_id reflects approximate insertion order across both types.
    op.execute(
        "UPDATE script_cue_association SET line_position = cue_id WHERE group_id IS NULL"
    )
    # All members of a group on the same (revision, line) share the same
    # line_position — use MIN(cue_id) for that group so the group's position
    # approximates when it was created relative to other cues on the line.
    op.execute(
        """
        UPDATE script_cue_association
        SET line_position = (
            SELECT MIN(sub.cue_id)
            FROM script_cue_association sub
            WHERE sub.group_id = script_cue_association.group_id
              AND sub.line_id = script_cue_association.line_id
              AND sub.revision_id = script_cue_association.revision_id
        )
        WHERE group_id IS NOT NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("script_cue_association", schema=None) as batch_op:
        batch_op.drop_column("line_position")

    # ### end Alembic commands ###
