"""Add default stage direction colour fields to user_settings

Revision ID: f1974e4e57d0
Revises: d11cd9306d4b
Create Date: 2026-07-07 10:53:28.601394

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f1974e4e57d0"
down_revision: Union[str, None] = "d11cd9306d4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("default_sd_text_colour", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("default_sd_background_colour", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_column("default_sd_background_colour")
        batch_op.drop_column("default_sd_text_colour")

    # ### end Alembic commands ###
