"""add script_mode to show

Revision ID: f365c2b2b234
Revises: fa8ee07e45fc
Create Date: 2025-12-30 12:25:29.715572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f365c2b2b234"
down_revision: Union[str, None] = "fa8ee07e45fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add script_mode column with backfill pattern for SQLite compatibility."""
    # Step 1: Add column as nullable
    with op.batch_alter_table("shows", schema=None) as batch_op:
        batch_op.add_column(sa.Column("script_mode", sa.Integer(), nullable=True))

    # Step 2: Backfill all existing shows with FULL mode (value = 1)
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE shows SET script_mode = 1 WHERE script_mode IS NULL"))

    # Step 3: Make column non-nullable
    with op.batch_alter_table("shows", schema=None) as batch_op:
        batch_op.alter_column("script_mode", existing_type=sa.Integer(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shows", schema=None) as batch_op:
        batch_op.drop_column("script_mode")

    # ### end Alembic commands ###
