"""Add crew, props and scenery tables and allocations

Revision ID: fa27b233d26c
Revises: 01fb1d6c6b08
Create Date: 2026-01-14 00:38:40.210710

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fa27b233d26c"
down_revision: Union[str, None] = "01fb1d6c6b08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crew",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_crew_show_id_shows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew")),
    )
    op.create_table(
        "props",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_props_show_id_shows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_props")),
    )
    op.create_table(
        "scenery",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_scenery_show_id_shows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenery")),
    )
    op.create_table(
        "props_allocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("props_id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["props_id"],
            ["props.id"],
            name=op.f("fk_props_allocation_props_id_props"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scene.id"],
            name=op.f("fk_props_allocation_scene_id_scene"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_props_allocation")),
    )
    op.create_table(
        "scenery_allocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scenery_id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scene.id"],
            name=op.f("fk_scenery_allocation_scene_id_scene"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenery_id"],
            ["scenery.id"],
            name=op.f("fk_scenery_allocation_scenery_id_scenery"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenery_allocation")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenery_allocation")
    op.drop_table("props_allocation")
    op.drop_table("scenery")
    op.drop_table("props")
    op.drop_table("crew")
    # ### end Alembic commands ###
