"""Add CrewAssignment model

Revision ID: fbb1b6bd8707
Revises: 625ac1e96e88
Create Date: 2026-02-04 02:47:35.857906

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fbb1b6bd8707"
down_revision: Union[str, None] = "625ac1e96e88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crew_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crew_id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("assignment_type", sa.String(), nullable=False),
        sa.Column("prop_id", sa.Integer(), nullable=True),
        sa.Column("scenery_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(prop_id IS NOT NULL AND scenery_id IS NULL) OR (prop_id IS NULL AND scenery_id IS NOT NULL)",
            name=op.f("ck_crew_assignment_exactly_one_item_type"),
        ),
        sa.ForeignKeyConstraint(
            ["crew_id"],
            ["crew.id"],
            name=op.f("fk_crew_assignment_crew_id_crew"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prop_id"],
            ["props.id"],
            name=op.f("fk_crew_assignment_prop_id_props"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scene.id"],
            name=op.f("fk_crew_assignment_scene_id_scene"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenery_id"],
            ["scenery.id"],
            name=op.f("fk_crew_assignment_scenery_id_scenery"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_assignment")),
        sa.UniqueConstraint(
            "crew_id",
            "scene_id",
            "assignment_type",
            "prop_id",
            name="uq_crew_prop_assignment",
        ),
        sa.UniqueConstraint(
            "crew_id",
            "scene_id",
            "assignment_type",
            "scenery_id",
            name="uq_crew_scenery_assignment",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crew_assignment")
    # ### end Alembic commands ###
