{
 "title": "DigiScript Server",
 "description": "Metrics used for monitoring the health of DigiScript server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests by Handler",
   "type": "bargauge",
   "description": "Total number of requests to the server grouped by handler",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (tornado_http_requests_total{handler!=\"DebugMetricsController\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "timeseries",
   "description": "Requests that are not 5xx or 4xx status codes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(tornado_http_requests_total{status!~\"5xx|4xx\"}[$__rate_interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Requests",
   "type": "timeseries",
   "description": "Requests that are 5xx or 4xx status codes",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(tornado_http_requests_total{status=~\"5xx|4xx\"}[$__rate_interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}