name: Lint & Format (ESLint + Prettier)
permissions:
  contents: read

on: [push]

jobs:
  run-node-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 24
    - run: npm ci
    - run: npm run ci-lint
  run-node-lint-electron:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./electron
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci
      - run: npm run ci-lint
